# Generated by Django 3.0 on 2022-06-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='horario_saída',
            new_name='horario_saida',
        ),
    ]
